### ISSUE TITLE
Document how to build vignettes with minidown

### ISSUE THREAD

**Issue by atusy** [atusy/minidown#21]
Based on a good example from @eddelbuettel 

https://github.com/eddelbuettel/littler/blob/master/vignettes/littler-examples.Rmd

Thanks @eddelbuettel for the suggestion at https://github.com/atusy/minidown/issues/18#issuecomment-704961104.

**Comment by eddelbuettel** [comment]
And I just noticed that that very example was not quite right (albeit in non-`minidown::water` parts)....

More documentation on this would still be appreciated.

**Comment by atusy** [comment]
Hmmm... That is partly the reason why I haven't started the documentation.
I have no experience with writing vignettes with non-default format.
As an experienced user, would you contribute by opening a PR?

(I also have a feeling that the documentation should rather be done in **rmarkdown** package, and that is the another reason.)

**Comment by atusy** [comment]
I just found the description in R Packages 2nd edition (WIP).

> https://r-pkgs.org/vignettes.html#vignette-metadata

I think this would be enough, and if you have something to add, I would suggest contributing the book.
Or is there any **minidown**-specific issue to be described?

**Comment by eddelbuettel** [comment]
It really is pretty easy.  Minimal is 

```yaml
---
title: "A Vignette Examples"
output:
  minidown::mini_document:
    framework: water
    toc: true
    toc_float: true
    code_folding:
      source: show
      output: show
      message: hide
      warning: hide
      error: hide
vignette: >
  %\VignetteIndexEntry{Vignette Example}
  %\VignettePackage{somePackage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

What makes a vignette are the five lines at the bottom.  Those are essentially fixed, two (refering to title and package it is indexed under) vary by package.

The YAML block, I found, really only has two lines that matter.  `Title`, obviously, and `Output` (which can be one line).

I opened the ticket because you and I went back and forth about what has to come after the `output` line, and it (currently, for what I knnow) is not done with just one line as we (currently) need to enumerate all options to get them right by RMarkdown.  That is something for you to look into.

Does this helps?  There isn't more, really.  You can add author and date, turn toc off relative to the example, ... but all that is _optional_ and just a matter of documenting it.

**Comment by eddelbuettel** [comment]
Needless to my ideal _would be_ the following:

```yaml
---
title: "A Vignette Example"
output: minidown::water
vignette: >
  %\VignetteIndexEntry{A Vignette Example}
  %\VignettePackage{somePackage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

i.e. we add an entry point `water` or `water_document` or ... in your package where you control the code which sets all defaults to 'reasonable' values (i.e. toc on, code fold on, ...).   That would be really really nice.  For non-vignette RMarkdown it would reduce to 

```yaml
---
title: "A Vignette Example"
output: minidown::water
---
```

which would rock really really hard.
