### ISSUE TITLE
is there a way to change the width of the floating toc and tabset?

### ISSUE THREAD

**Issue by ahdee** [atusy/minidown#71]
Hi, is there way to override the default width? 
So on the left floating TOC I want it to flush all the way to the left with only 20px with a max of 300px, but the right container where all the tabset are I would like to set it to 1800 px.  Is there anyway to do this? thanks. 
A

**Comment by atusy** [comment]
TOC layouts are defined by CSS rules in the following file. You can override it to match your needs.
https://github.com/atusy/minidown/blob/master/inst/rmarkdown/html/styles/feat-toc-float.css

Although I do not fully understand your request, maybe you can start from the following CSS.

````css
:root {
  --toc-width: 300px;
}
main {
  margin: 0 0 0 20px
}
header, article {
  width: 1800px;
  padding: 0 0 0 4rem;
}
````
